function displayQuote() {
    const motivationalQuotes = [
        "Believe you can and you're halfway there. -Theodore Roosevelt",
        "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
        "It always seems impossible until it's done. -Nelson Mandela",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -Christian D. Larson",
        "Your time is limited, don't waste it living someone else's life. -Steve Jobs",
        "Act as if what you do makes a difference. It does. -William James",
        "Don't be afraid to give up the good to go for the great. -John D. Rockefeller",
        "Life is what happens when you're busy making other plans. -John Lennon",
        "Don't cry because it's over, smile because it happened. -Dr. Seuss",
        "The best way to predict the future is to invent it. -Alan Kay",
        "Your life does not get better by chance, it gets better by change. -Jim Rohn",
        "Opportunity does not knock, it presents itself when you beat down the door. -Kyle Chandler",
        "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
        "The only way to achieve the impossible is to believe it is possible. -Charles Kingsleigh",
        "In the middle of difficulty lies opportunity. -Albert Einstein",
        "The future depends on what you do today. -Mahatma Gandhi",
        "It's not whether you get knocked down, it's whether you get up. -Vince Lombardi",
        "Do not wait for leaders; do it alone, person to person. -Mother Teresa",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. -Ralph Waldo Emerson",
        "Do not let what you cannot do interfere with what you can do. -John Wooden",
        "You miss 100% of the shots you don't take. -Wayne Gretzky",
        "The only limit to our realization of tomorrow will be our doubts of today. -Franklin D. Roosevelt",
        "The best way to predict your future is to create it. -Peter Drucker",
        "Success is not in what you have, but who you are. -Bo Bennett",
        "The only way to do great work is to love what you do. -Steve Jobs",
        "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. -Chantal Sutherland",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. -Roy T. Bennett",
        "The purpose of our lives is to be happy. -Dalai Lama",
        "Don't count the days, make the days count. -Muhammad Ali",
        "Life is 10% what happens to us and 90% how we react to it. -Charles R. Swindoll",
        "I find that the harder I work, the more luck I seem to have. -Thomas Jefferson",
        "It always seems impossible until it's done. -Nelson Mandela",
        "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
        "Believe you can and you're halfway there. -Theodore Roosevelt",
        "Don't limit your challenges. Challenge your limits. -Jerry Dunn",
        "Dream big and dare to fail. -Norman Vaughan",
        "I never dreamed about success. I worked for it. -Estee Lauder",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston Churchill",
        "If you want to achieve greatness stop asking for permission. -Anonymous",
        "Your attitude, not your aptitude, will determine your altitude. -Zig Ziglar",
        "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
        "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
        "Believe you can and you're halfway there. -Theodore Roosevelt",
        "Don't limit your challenges. Challenge your limits. -Jerry Dunn",
        "Dream big and dare to fail. -Norman Vaughan",
        "I never dreamed about success. I worked for it. -Estee Lauder",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston Churchill",
        "If you want to achieve greatness stop asking for permission. -Anonymous",
        "Your attitude, not your aptitude, will determine your altitude. -Zig Ziglar",
        "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
        "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
        "Believe you can and you're halfway there. -Theodore Roosevelt",
        "Don't limit your challenges. Challenge your limits. -Jerry Dunn",
        "Dream big and dare to fail. -Norman Vaughan",
        "I never dreamed about success. I worked for it. -Estee Lauder",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston Churchill",
        "If you want to achieve greatness stop asking for permission. -Anonymous",
        "Your attitude, not your aptitude, will determine your altitude. -Zig Ziglar",
        "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
        "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
        "Believe you can and you're halfway there. -Theodore Roosevelt",
        "Don't limit your challenges. Challenge your limits. -Jerry Dunn",
        "Dream big and dare to fail. -Norman Vaughan",
        "I never dreamed about success. I worked for it. -Estee Lauder",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston Churchill",
        "If you want to achieve greatness stop asking for permission. -Anonymous",
       ];

    const random = Math.floor(Math.random() * motivationalQuotes.length);
    const selected_Quote = motivationalQuotes[random];
    
    document.getElementById('Quote').innerHTML = selected_Quote;
    }
// setInterval(displayQuote,5000)
